name: Weekly Docker Build

on:
  schedule:
    # Runs at 00:00 UTC every Monday
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.filter.outputs.changes_detected }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for changes in the last week
        id: filter
        run: |
          git fetch origin
          CHANGES=$(git diff --name-only HEAD $(git rev-parse HEAD~1))
          if [ -z "$CHANGES" ]; then
            echo "No changes detected"
            echo "::set-output name=changes_detected::false"
          else
            echo "Changes detected"
            echo "::set-output name=changes_detected::true"
          fi

  build-and-push:
    needs: check-for-changes
    #if: needs.check-for-changes.outputs.changes_detected == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: WantClue/public-pool:latest
          platforms: linux/arm64

      - name: Checkout repository
        uses: actions/checkout@v3

